# Generated by Django 2.0.3 on 2020-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('user_img', models.ImageField(blank=True, upload_to='user_images')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('user_country', models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('USA', 'USA')], max_length=50)),
                ('user_pass', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('added_by', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User Information',
            },
        ),
    ]
