# Generated by Django 2.0.3 on 2020-05-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
            ],
            options={
                'verbose_name': 'Gift Card  Generate',
                'verbose_name_plural': 'Gift Card  Generate',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product category',
            },
        ),
        migrations.CreateModel(
            name='ProductSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('bdt_unit_price', models.FloatField(default=0)),
                ('unit_sales_price', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.ProductCategory')),
            ],
            options={
                'verbose_name': 'Product Setup',
                'verbose_name_plural': 'Product Setup',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.ProductSetup')),
            ],
            options={
                'verbose_name': 'Stock Information',
                'verbose_name_plural': 'Stock Information',
            },
        ),
    ]
