# Generated by Django 2.0.3 on 2020-05-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0002_giftcardgenerate_productcategory_productsetup_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.ProductSetup')),
            ],
            options={
                'verbose_name': 'Purchase Information',
                'verbose_name_plural': 'Purchase Information',
            },
        ),
    ]
