# Generated by Django 2.0.3 on 2020-05-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0005_saleshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_country', models.CharField(choices=[('Bangladesh', 'Bangladesh'), ('USA', 'USA')], max_length=50)),
                ('start_amount', models.FloatField(default=0)),
                ('end_amount', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
            ],
            options={
                'verbose_name': 'Discount Setup',
                'verbose_name_plural': 'Discount Setup',
            },
        ),
    ]
