# Generated by Django 2.0.3 on 2020-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0006_discountsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsetup',
            name='discount_parcentage',
            field=models.FloatField(default=0),
        ),
    ]
