# Generated by Django 2.0.3 on 2020-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0007_discountsetup_discount_parcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='invoice_no',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
