# Generated by Django 2.0.3 on 2020-05-30 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0008_saleshistory_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=30, unique=True)),
                ('sales_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('net_price', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isoapp.UserInfo')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='remark',
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='invoice_no',
            field=models.CharField(max_length=30),
        ),
    ]
