# Generated by Django 2.0.3 on 2020-05-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0009_auto_20200530_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_price',
        ),
    ]
