# Generated by Django 2.0.3 on 2020-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0010_remove_sales_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountsetup',
            name='discount_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
