# Generated by Django 2.0.3 on 2020-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isoapp', '0012_auto_20200530_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
